# Generated by Django 3.0.5 on 2020-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data_rate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
