# Generated by Django 3.0.5 on 2020-05-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200503_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datum',
            options={'ordering': ['id'], 'verbose_name': 'datum', 'verbose_name_plural': 'data'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['-time'], 'verbose_name': 'metadata', 'verbose_name_plural': 'metadata'},
        ),
    ]
