# Generated by Django 3.0.5 on 2020-05-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('application', '0001_initial'),
        ('data', '0003_auto_20200503_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datum',
            options={'ordering': ['-id'], 'verbose_name': 'datum', 'verbose_name_plural': 'data'},
        ),
        migrations.AddField(
            model_name='datum',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='datum',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
