# Generated by Django 3.0.5 on 2020-05-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('device', '0001_initial'),
        ('data', '0004_auto_20200510_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='dev_id',
        ),
        migrations.AlterField(
            model_name='datum',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AlterField(
            model_name='datum',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
